### ISSUE TITLE
disabled doesn't work

### ISSUE THREAD

**Issue by TwanLuttik** [jiscaskalov/slime-chunk-viewer#1]
When you walk around and you have it disabled, it will update new chunks in the far distance

Like this
![CleanShot 2024-02-03 at 21 57 18@2x](https://github.com/jiscaskalov/slime-chunk-viewer/assets/19343894/2b5f313c-de80-4f83-affb-aad647d146a0)

**Comment by jiscaskalov** [comment]
This is now fixed in an update that I will release soon

**Comment by jiscaskalov** [comment]
Just released 0.0.2, which fixes this issue and includes many new rendering features
